name: NANA-Develop

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GitHubMail: "happymarv3@gmail.com"
  GitHubName: "happy-lappy"

jobs:
  nanadevelop:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
      - name: Setup Py3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Gather repo
        run: |
          git clone "https://${{ secrets.GH_TOK }}@github.com/happy-lappy/nana-bot" nana-dev || exit 1
          git clone "https://${{ secrets.GH_TOK }}@github.com/happy-lappy/nana-db.git" dbase || exit 1
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: "nanadev"
      - name: Build wheels
        timeout-minutes: 330
        continue-on-error: true
        run: |
          cd nana-dev
          pip3 install Pyrogram==1.4.16
          python3 -m bsbz
      - name: Quality Control
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} lupo
          cd lupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > buildid.txt
          git add buildid.txt
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/${GITHUB_REPOSITORY}" HEAD:main || exit 1
